const Discord = require("discord.js");
const client = new Discord.Client();
const config = require("./config.json");
const fs = require("fs");
const quotes = [
"[+TSM-GOD] youre the one who uses asteroids for get laid",
"[02:29:12] <WoW-TSM> some of my matches were telebroadcasting there",
"[01:58:06] <TSM-GOD> when i talk shit is because you need a warning cos im a competitor like football manager",
"[01:57:12] <TSM-GOD> i talk shit when you deserves \ [01:57:22] <TSM-GOD> like a father who punish his sons",
"[23:57] <TSM-GOD> you cant make a headshot when youre crunched",
"[11:58:50] <TSM-GOD> the mexicans invent the video games with the little stick",
"[01:19:01] <TSM-GOD> the guy eat like 3 cigarretes boxes per day",
"[11:58:42] <TSM-GOD> i cant travel to the border just for a videogame \ [11:58:50] <TSM-GOD> i maybe get shoot by those fucking racist",
"[01:30:24] <TSM-GOD> i have all the ladies with his mouth open anytime im a real model asshole",
"[11:53:24] <TSM-GOD> im gona trade pink ds for xbox 360",
"[10:09:19] <TSM-GOD> batman legos and pure was about shit bicicletes",
"[11:18:09] <TSM-GOD> all the kids in the hood wana come to play my xbox",
"[11:49:02] <TSM-GOD> theres nothing better that work out your muscles while listen some too pack oldschool gangster rap",
"[01:43:30] <TSM-GOD> you can talk all the shit you want, but you have never be like me \ [01:43:05] <TSM-GOD> is like in real life, when youre a winner everybody want to take a piece of the pie make fake bullshit and be jealousness",
"[11:47:34] <TSM-GOD> in my house we are always me and my niggas",
"[01:46:37] <TSM-GOD> when they grow up they gona say in the future, damn that guy tsm was right i should have do something with my life besides be a fucking computer weirdo antisocial",
"[11:44:34] <TSM-GOD> did you ever hear too pack spic \ [11:44:38] <TSM-GOD> hes amagazing \ [11:46:38] <TSM-GOD> old school hip hop from the gettos",
"[11:17:42] <TSM-GOD> im one of the few people in mexico \ [11:17:48] <TSM-GOD> with xbox 360",
"<THESEXIESTMAN> im gona writte a book actually",
"[02:57:43] <TSM-GOD> my fist are like prayers of jesus ready to kick your ass",
"[10:51:02] <+TSM-GOD> i wanted to punch the guy who gets teletransportated in the flag stand",
"<+echo|HV> tsm you want to suck toms penis for new xbox games ? \ [21:40:26] <+TSM-GOD> what games",
"[01:31:30] <TSM-GOD> if i see you in front of me il throw you a punch to your nouse and it bleeds",
"[01:02:26] <TSM-GOD> if you got muscles \ [01:02:27] <TSM-GOD> show it \ [01:02:39] <TSM-GOD> prove yourself bitch",
"[01:03:43] <TSM-GOD> il cum your tees so they will be more rotten",
"[10:57:34] <TSM-GOD> im listening this album \ [10:57:49] <TSM-GOD> niggas with attitue \ [10:57:51] <TSM-GOD> for inspiration",
"<+TSM-GOD> im here doing chicken dance just to mess with you in front of your nerd face",
"[06:45:48] <TSM-GOD> .join \ [06:45:52] <TSM-GOD> lets make a pug to remember",
"[12:16:57] <+WoW-TSM> i dont belive nothing until i say it with my real eyes",
"<+TSM-GOD> rap comes from the heart straight to the gargant",
"[01:04:48] <Thesexiestman> you cant stand always in the same place \ [01:04:52] <Thesexiestman> with the same people \ [01:04:42] <Thesexiestman> in life you must change constantly your places",
"[12:18:22] <Thesexiestman> just follow the rivers",
"[06:12:31] <Thesexiestman> you fucking anemias bitch \ [06:12:36] <Thesexiestman> anorexican",
"[02:08:47] <WoW-TSM> i teach ppl to play thats why im gona make my own Ut training camp \ [02:08:49] <WoW-TSM> in youtube",
"[01:10:15] <Thesexiestman> but one fishes grave was in the batroom \ [01:10:20] <Thesexiestman> flushing the toilet \ [01:10:50] <Thesexiestman> everything that dies \ [01:10:56] <Thesexiestman> becomes in life in other places \ [01:11:03] <Thesexiestman> a rock \ [01:11:07] <Thesexiestman> is life \ [01:11:11] <Thesexiestman> same as the ground \ [01:11:19] <Thesexiestman> or the little microbies in your bed",
"<TSM-Mexicoschampion> my videos are a lesson in life about how a normal person with a lot of training and self courage can become one of the top players here",
"<TSM-Mexicoschampion> in mexico you must work in police if you want to end your collegiatures",
"<TSM-THEMEXICOSCHAMP> i got the muscles of an ancient aztec warrior and the handsomeness of a french person",
"<TSM-THEMEXICOSCHAMP> im a rich persons but i prefer to throw my money to man of the streets",
"<TSM-GOD> when the sun goes down and the moon lights my muscles",
"<TSM-GOD> owned well from behind",
"[21:19] <+TSM-GOD> il defend my gold with my lifes \ [21:20] <+TSM-GOD> like a laprechhaunt",
"<TSM-Legend> i bought my car thanks to ut",
"<TSM-Legend> im a celebrity here in mexico",
"<TSM-GOD> owned from the skies above",
"<TSM-GOD> i rice up from the ashes like the fenix",
"<+Ultranova> Cocksuckers dont join the pug if you will not play <+TSM-GOD> Calm down you Ape",
"<TSM-GOD> Davis you play so good that if you keep playing like that you will be my succesor",
"TSM Answers: I have another 3 professions besides be a professional UT player",
"<TSM-GOD> i have a heart of a brave lion",
"<TSM-GOD> Once time i went to boxing gym and let the kids suck some of my big dick",
"<+TSM-GOD> spain arent latinos <+TSM-GOD> youre so fucking ignorant dude",
"[03:12] <@TSM-GOD> my name was in the last prints of UT mintek says \ [03:12] <@TSM-GOD> featuring TSM \ [03:12] <@TSM-GOD> in the boxes of ut 99",
"<@TSM-GOD> I retire ut players",
"<+TSM-GOD> *putting out my belt to punish little brock*",
"[03:07] <@TSM-GOD> idont use nerd glasses \ [03:08] <@TSM-GOD> i got vission of an eagle",
"[05:26:31] <TSM-GOD> in my schoole i am like the celebreti aprentise",
"<+TSM-GOD> remember this words mintek forever <+TSM-GOD> even when everything is lost you need to use the earth of a lion always <+TSM-GOD> that words<+TSM-GOD> make me what i am now<+TSM-GOD> only fucking losers like ciro gets angry when you try to help him those people are the cancer of the world",
"[02:53] <@TSM-GOD> watch that @ in my nickname \ [02:53] <@TSM-GOD> it means i am the law here now",
"<+TSM-ThepeoplesChamp> you think youre thought cos you got @ ... jesus and me the perfect offense",
"<TSM-GOD> !8ball im the best ut player from latinoamerica <@ChanServ> TSM-GOD: Are you out of yout MIND?",
"<+TSM-GOD> youre just a phatologycal liar",
"[02:21:46] <TSM-GOD> all the girls in my school see me as the champ of games",
"[07:52:14] <TSM-GOD> com on and join already and get killed by the lion",
"<TSM-Legend> [10:24:36] im like the shark that swims in the silent",
"[05:08] <+TSM-GOD> are they swords from the age of dragons? \ [05:09] <+TSM-GOD> in europe was were the people fight dinosaurs and dragons \ [05:09] <+TSM-GOD> in the old ages",
"<DAREALSEXIESTMAN> you will run when you see my muscles",
"<REALSEXIESTMAN> WHEN I GO TO NIGHT CLUBS I ALWAYS GET 1 OR 2 WOMANS",
"<+SEXIESTMAN4EVER> your mom have animalips",
"<+SEXIESTMAN4EVER> dont call me sexyboy you fucking nixon",
"<DAREALSEXIESTMAN> my ut honour is more important to me than all my girls at school",
"<TSM-GOD> im focusin all my nowlege to UT like the chinse monks",
"<TSM-Legend> I just go time for one more question sorry, the message is clear, follow the eagle of freedom, follow what the heart says and listen to the messages of the nature,the river is the greatest master when youre in troubles",
"<DAREALSEXIESTMAN> i play 6 months in tdmpickups and when i come back to ctf it was real easy for me",
"<@suga|51> is that you in the picture holding hte trophy \ <+SEXIESTMAN4EVER> yes why \ <+sus> because you are not a sexy man \ <+sus> :\ \ <+SEXIESTMAN4EVER> im not that guy \ <@Solo][> yeah ur ugly \ <+SEXIESTMAN4EVER> dumbass \ <+SEXIESTMAN4EVER> stupid fuck \ <+sus> just said it was you \ <+sus> i think it is you now \ <+sus> because you said it was \ <+SEXIESTMAN4EVER> i never say that",
"<+THEREALSEXIESTMAN> you gona open your nerd comic book store tomorrow \<+THEREALSEXIESTMAN> stupid weirdo",
"<+THEREALSEXIESTMAN> youre the fucking loser \ <+THEREALSEXIESTMAN> selling shit comic spider man comic books",
"<%TSM-LEGENDA> well if you make this channel to learn about my philosophys you can make it 1 vs 1 so i can teach you some new moves",
"<@[51]chicken-> you\'re full of shit <+TSM-GOD> whats wrong with that?",
"<+REALSEXIESTMAN> my next plan is retired players <+REALSEXIESTMAN> challenges to a death challenge",
"<%TSM-LEGENDA> i am the king youre the peons",
"<%TSM-LEGENDA> all i say has been glorified, again it proves that a normal mexican guy can be smartert than all the fucking american computer workers from usa",
"<+THEREALSEXIESTMAN> i was in the army for 9 years <+THEREALSEXIESTMAN> we dont like fucking pussys",
"[04:43:05] <TSM-LEGENDA> give me more publicity assholes",
"[04:44:42] <TSM-LEGENDA> now youre goiginto the patheticism",
"<+THEREALSEXIESTMAN> we have army dumbfuck <+Seinfeld`Curse> a terrible army<+THEREALSEXIESTMAN> i injury <+THEREALSEXIESTMAN> my arm <+THEREALSEXIESTMAN> break the big bones <+THEREALSEXIESTMAN> on a practice",
"<TSM-ThepeoplesChamp> but i will owned him with intelligence | <Lenneth|^> if a gay guy jumped on your back would you beat him off TSM? <TSM-ThepeoplesChamp> yeah <TSM-ThepeoplesChamp> so bad",
"<%TSM-LEGENDA> when i won the teamwarfare league in 2006 you can see the webpage and put HMW CLAN i even beat flux clan called 51",
"<+TSM-KIngOfLatinos> and im gona kick your thiny ass \ <+melissa7> thiny LOL X D \ <+TSM-KIngOfLatinos> melissa \ <+TSM-KIngOfLatinos> i can move the muscles of my ass",
"<THESEXIESTMAN-dArealdEal> i call my muscles friends \ <THESEXIESTMAN-dArealdEal> and i got a lot of muscles \ <THESEXIESTMAN-dArealdEal> bitch",
"<+TSM-LatinoLegend> an average person got like \ <+TSM-LatinoLegend> 4.000 muscles in body \ <+TSM-HoF|lkemas> nice TSM what about you \ <+TSM-LatinoLegend> i got like 8.000 so i think i got more muscles \ <+TSM-LatinoLegend> than friends",
"<TSM-KingofMexico> my muscles are like arnold shwarsanagers",
"<+TSM-Mexicoschampion> of couyrse im not fat \ <+TSM-Mexicoschampion> im an atlethe \ <+TSM-Mexicoschampion> i prefer die to be fat",
"<+TSM-Mexicoschampion> your stinky disgustes me",
"<TSM-GOD> i dare you to challenge me to the fight of the streets",
"<@TSM-detox> i say us 3 celebrate this victory with a giant tub of chocolate pudding \ <+TSM-LatinoLegend> that will make your stomach hurts \ <+TSM-LatinoLegend> we can celebrate with something healty \ <+TSM-LatinoLegend> we can have a celebration with cucumber water \ <+TSM-LatinoLegend> and working out our muscles",
"<THEREALSEXIESTMAN> eat lots of beans for muslces and all the girls will want you",
"<TSM-LEGENDA> this is a chanel with my stuff i make i can talk to mirc police and they will shut down this crap",
"<+TSM-LatinoLegend> if tom keeps drinking and smoking and eating shitfood like that hes gona die at 50.",
"<+TSM-ThepeoplesChamp> cucumber water \ <+TSM-ThepeoplesChamp> will clean your body \ <+TSM-ThepeoplesChamp> and soul",
"<+TSM-ThepeoplesChamp> cucumber will give you perfect skin and will revive your body from inside",
"<+TSM-ThepeoplesChamp> i got lots of muscles for everybody \ <+TSM-ThepeoplesChamp> no need to fight",
"<+TSM-ThepeoplesChamp> brock only thing he does is eat macdonals like a fucking pig \ <+TSM-ThepeoplesChamp> thats a very boring unleathy life",
"<@detox> bah smokers infesting our pugs \ <+TSM-ThepeoplesChamp> yeah man \ <+TSM-ThepeoplesChamp> hes not fucking healthy and he kills the woods \ <+TSM-ThepeoplesChamp> with his smoke",
"<+TSM-ThepeoplesChamp> when you smoke \ <+TSM-ThepeoplesChamp> you killyourself your breath your stomach and your nouse but worst than that \ <+TSM-ThepeoplesChamp> when you smoke the air of the cigarretes contaminates the woods and the silvester animals \ <+TSM-ThepeoplesChamp> youre like cancer \ <+TSM-ThepeoplesChamp> for the pulmons \ <+TSM-ThepeoplesChamp> of this world",
"<+TSM-ThepeoplesChamp> i do my hands in a model",
"<+TSM-ThepeoplesChamp> in my days in the streets like i got no mmoney for the gym i trained throwing guys and cutting wood like the guy in the video",
"<+SEXIESTMAN-MostfamousUTplayer> i do kickboxing and box \ <+SEXIESTMAN-MostfamousUTplayer> try punch \ <+Seinfeld`Curse> i got a gun \ <+SEXIESTMAN-MostfamousUTplayer> i can kick your gun \ <+SEXIESTMAN-MostfamousUTplayer> and then with my fist broke your nouses",
"<+lkemas> TSM, what would you do if you meet a man in the streets with a green gun \ <+THESEXIESTMAN-dArealdEal> it depends if his a kid \ <+THESEXIESTMAN-dArealdEal> a normal man \ <+THESEXIESTMAN-dArealdEal> or a old man \ <+THESEXIESTMAN-dArealdEal> if hes a kid i run away",
"<+DAREALSEXIESTMAN> in the street like 42 fights \ <+DAREALSEXIESTMAN> since the highschool \ <+DAREALSEXIESTMAN> all fights in street counts like a loose",
"<+THESEXIESTMAN-dArealdEal> my fists are considered as a weapon by the mexican law actually",
"<+THESEXIESTMAN-dArealdEal> i almost won the golden globes of mexico but \ <+THESEXIESTMAN-dArealdEal> i get injured",
"<+TSM-LatinoLegend> you shit your pants and call your mom if i challenge you to a street fight",
"<TSM-Mexicoschampion> if you were in my face i will punch you so hard you cant even remember",
"<+TSM-Mexicoschampion> when i was in jail \ <+TSM-Mexicoschampion> people spitting to the weakest person \ <+TSM-Mexicoschampion> i defended lots of bitches in prision \ <+TSM-Mexicoschampion> the ddudes like brock will commit suicide before go to jail",
"<+TSM-Mexicoschampion> i will kick your doors of your house \ <+TSM-Mexicoschampion> until you come out to face me \ <+TSM-Mexicoschampion> in a street figght",
"<+TSM-Mexicoschampion> in kickboxing they always uses the expresion heart of a lion before the fights \ <+TSM-Mexicoschampion> you must program yourself with that words everyday \ <+TSM-Mexicoschampion> face the life like a lion",
"<+TSM-ThepeoplesChamp> there is a reason why i exist to protect people from assholes like you",
"<+TSM-ThepeoplesChamp> if you call me spic to my face you will be shitting in your pants right now \ <+TSM-ThepeoplesChamp> your nerd cats cant save you now",
"<@TSM-ThepeoplesChamp> i heard that gays are great fighters but im not scarred",
"<@TSM-ThepeoplesChamp> if a gay jumps in my back i will take his face and smashes his face into the walls \ <@TSM-ThepeoplesChamp> in aikido i learn a nice move \ <@TSM-ThepeoplesChamp> i can move the muscles of my ass before \ <@TSM-ThepeoplesChamp> he can do that",
"<+TSM-LatinoLegend> but friends who can give his life to save me are detox and dragon",
"<+TSM-ThepeoplesChamp> at least he got real female friends you got nothing seinfield scum \ <+TSM-ThepeoplesChamp> in the farm you cant even know real people only talk with animals",
"<+TSM-Kingofmexico> mexican culture is about temples, pyramids, historis \ <+detox> mexican culture is just tequila, pinatas, and donkey shows \ <+TSM-Kingofmexico> american culture is just fucking spiderman shit, gay cowboys and hamburgers.",
"<+TSM-LatinoLegend> i can speak other 4 lenguajes \ <+TSM-LatinoLegend> franch spanish mexican and american \ <+TSM-LatinoLegend> my karate master teach me some words in korean but just a little \ <+TSM-LatinoLegend> i speak cling- on too",
"<+TSM-MEXICOSNUMBER1> french got the style and handsomnes \ <+TSM-MEXICOSNUMBER1> mexico got the attitude of a warrior",
"<+xios> wat \'rices from the ashes\' mean? \ <+TSM-ThepeoplesChamp> wake from the death \ <+TSM-ThepeoplesChamp> like when \ <+TSM-ThepeoplesChamp> youre having abeating in boxing and then \ <+TSM-ThepeoplesChamp> you get stamina from the skies and you won the match",
"<@Joe> ill 1v1 you if its DM not ctf \ <+REALSEXIESTMAN> youre my friend joe \ <+REALSEXIESTMAN> i dont want to humillate you \ <@Joe> whoa",
"<TSM> i win and i can help you",
"<TSM-BLOG> Fishes are good for concentration and focus, before a 1 vs 1 duel you must consult the fishes so they can give you wiseness and relax yourself while you see them swing.",
"<TSM-Legend> someone hack my bullets",
"<THESEXIESTMAN-dArealdEal> well actually my pug stats are 85% won \ <THESEXIESTMAN-dArealdEal> i have all the ss of my games \ <THESEXIESTMAN-dArealdEal> in here i just lost a pug \ <THESEXIESTMAN-dArealdEal> in all the pug channel history",
"<TSM-BLOG> Well there is a reason why TSM matches are the most famous in the land of the videogames, i almost beat mellisa in one of the most exciting duels ever in the history of Unreal Tournament.",
"[22:51] <+TSM-GOD> i was in a rap fight \ [22:51] <+TSM-GOD> thats how i get respected by the black comunity \ [22:51] <+TSM-GOD> i won",
"<+TSM-LatinoLegend> im training and the fruits are growing up good",
"<+Nark> not my exact car | <+Nark> but i owna 3000gt vr4 | <+TSM-ThepeoplesChamp> you got not even a bircycle | <+TSM-ThepeoplesChamp> you fucking child poor playing old videogames | <+TSM-ThepeoplesChamp> i mean a biciclete",
"<+TSM-Mexicoschampion> i calculate the moment exactly when the opponent make his steps",
"<+Nark> not my exact car \ <+Nark> but i owna 3000gt vr4 \ <+TSM-ThepeoplesChamp> you got not even a bircycle \ <+TSM-ThepeoplesChamp> you fucking child poor playing old videogames \ <+TSM-ThepeoplesChamp> i mean a biciclete",
"<+TSM-Mexicoschampion> damn my back is sweety for so much games in my server",
"<TSM-KingofMexico> noobs pay me for advice and i show them the best training",
"<+TSM-Mexicoschampion> i never type \ <+TSM-Mexicoschampion> those are my keibinds",
"<+TSM-Mexicoschampion> listen here, if you want to make the best combos \ <+TSM-Mexicoschampion> you need to practice at 300 speed \ <+TSM-Mexicoschampion> and then slow down the game to -40 speed \ <+TSM-Mexicoschampion> i train like that 4 weeks \ <+TSM-Mexicoschampion> are changing to normal to profesional",
"<+TSM-Mexicoschampion> he cant even kill me \ <+TSM-Mexicoschampion> i was just making fun of him \ <+TSM-Mexicoschampion> eating some sushi and wine while he tries to kill me",
"<+TSM-Mexicoschampion> some people like tyson and paquiao are good at boxing \ <+TSM-Mexicoschampion> im good at ut",
"<+lkemas> TSM, i've been training with 850 speed, is this overkill? Should i go back to mere 300 speed to improve my combos in movement? \ <+TSM-ThepeoplesChamp> well ikemas \ <+TSM-ThepeoplesChamp> im not here now \ <+TSM-ThepeoplesChamp> so i cant give you advices \ <+TSM-ThepeoplesChamp> *not here *",
"<+TSM-ThepeoplesChamp> my brother play half of all \ <+TSM-ThepeoplesChamp> my pugs",
"<+TSM-ThepeoplesChamp> was a tought match \ <+TSM-ThepeoplesChamp> i get sweaty that match in the back",
"<+TSM-ThepeoplesChamp> well me and style we come together i one package i cant be me without have style",
"<+TSM-Mexicoschampion> i have a jacket exactly \ <+TSM-Mexicoschampion> like the one \ <+TSM-Mexicoschampion> who uses brad pitt \ <+TSM-Mexicoschampion> in the fight club",
"<+TSM-Mexicoschampion> youre jealous cos i can buy a simpson chair living in mexico",
"<+TSM-Mexicoschampion> i got a new cocodrile shoes \ <+TSM-Mexicoschampion> you asshole \ <+TSM-Mexicoschampion> cocodrile letter boots \ <+TSM-Mexicoschampion> cocodrile skin boots \ <+AnceriZ> whats a cocodrile? \ <+TSM-Mexicoschampion> reptile \ <+TSM-Mexicoschampion> that swings in the water",
"<+TSM-ThepeoplesChamp> i still have my football jacket of the collage \ <+TSM-ThepeoplesChamp> i call it the sexiestman jacket \ <+TSM-ThepeoplesChamp> i use it for hard games \ <+TSM-ThepeoplesChamp> in ut",
"<+TSM-LatinoLegend> il fuck your mom \ <+TSM-LatinoLegend> then your sisters \ <+TSM-LatinoLegend> then il fuck you \ <+Kaetzchen> my mom is dead \ <+TSM-LatinoLegend> im gona fuck her grave",
"<+TSM-Mexicoschampion> homosexual fag \ <+TSM-Mexicoschampion> mintek was \ <+TSM-Mexicoschampion> fucking me",
"<+nark> i may suck at a video game tsm but you suck dick in real life \ <+TSM-Mexicoschampion> well nark youre here at 11:00 in a hot friday night \ <+TSM-Mexicoschampion> whos the loser now? \ <+Brock> so are you tsm \ <+TSM-Mexicoschampion> just like i say in speedpug \ <+TSM-Mexicoschampion> i just comeback from the club \ <+TSM-Mexicoschampion> im tired of sex with all those womens everyweekend",
"<+TSM-Mexicoschampion> you call your cats girlfriends \ <+TSM-Mexicoschampion> and masturbate with them",
"<+TSM-Mexicoschampion> suck my dick \ <+Brock> ok ill suck it \ <+TSM-Mexicoschampion> no way \ <+Brock> u asked me to \ <+Brock> dumbass \ <+TSM-Mexicoschampion> my dick is my most presious thing",
"<THEREALSEXIESTMAN> i go walk down the streets and i hear girls calling my name i cant help it",
"<+TSM-ThepeoplesChamp> i dont wana see your fat nerd body naked dude \ <+TSM-ThepeoplesChamp> detox told me you was strong like a greek good",
"<+TSM-ThepeoplesChamp> i take off my t shirt but i dont know why",
"<@ABot>  PUG has been filled. Type !captain to become a captain (40secs) \ <+TSM-ThepeoplesChamp> DAMN i was giving a webcam show to one of my girls \ <+TSM-ThepeoplesChamp> but the asshole writte join",
"<+TSM-ThepeoplesChamp> if you take the eyes and the nouses and the lips from the ultranooba face it just looks like a big bean not even a real face why you call him sexy",
"<+AnNiHiLaToR[HERO]> god i hope tsm never has sex...and passes his retarded genes.. \ <+TSM-ThepeoplesChamp> actually i get tired of have lots of sex \ <+TSM-ThepeoplesChamp> thats why i come here \ <+TSM-ThepeoplesChamp> fucking nerdo",
"<+TSM-ThepeoplesChamp> my dick will break your teeth \ <+TSM-ThepeoplesChamp> my muscular dick \ <+TSM-ThepeoplesChamp> will break your smile",
"<+TSM-ThepeoplesChamp> i bet lineth have never got a women in hes bed \ <+TSM-ThepeoplesChamp> he well get scared as shit \ <+Lenneth|^> you know the chick in that pic that you used \ <+TSM-ThepeoplesChamp> hahahahaha \ <+TSM-ThepeoplesChamp> shes not even loocking at you \ <+TSM-ThepeoplesChamp> you must fart lots of times",
"<+THEREALSEXIESTMAN> im an atlethe i want people happiness",
"<+THESEXIESTMAN-dArealdEal> rocky is a movie about know yourself \ <+THESEXIESTMAN-dArealdEal> the messages \ <+THESEXIESTMAN-dArealdEal> rocky gives to his son \ <+THESEXIESTMAN-dArealdEal> is the key of life",
"<+TSM-THEKING> for a winner theres always a tomorrow \ <+TSM-THEKING> for a loser \ <+TSM-THEKING> not",
"<+TSM-Mexicoschampion> only thing a man got are his honour and his memorys",
"<+TSM-Mexicoschampion> in my life i set objetives \ <+TSM-Mexicoschampion> one objetive was boxing \ <+TSM-Mexicoschampion> one objetive was modeling \ <+TSM-Mexicoschampion> one objetive was to prepare myself to hard life \ <+TSM-Mexicoschampion> when i complete those objetives \ <+TSM-Mexicoschampion> i can feel like a winner \ <+TSM-Mexicoschampion> amen",
"<+TSM-ThepeoplesChamp> youre living in the real world dragon the real world isnt nice \ <+TSM-ThepeoplesChamp> you cant stop throwing punches in your life",
"<+TSM-ThepeoplesChamp> get out of your house son \ <+TSM-ThepeoplesChamp> you live in a bubble of dreams",
"<+TSM-LatinoLegend> if i die \ <+TSM-LatinoLegend> people gona make a festival for me \ <+TSM-LatinoLegend> in the streets and ut \ <+TSM-LatinoLegend> if you die no one cares",
"<+TSM-Mexicoschampion> im a respected champion man",
"<@TSM-Mexicoschampion> in mexico some people considers me a national hero",
"<+TSM-ThepeoplesChamp> my youtube channel got one prize \ <+TSM-ThepeoplesChamp> most viewed gurus channel in mexico \ <+TSM-ThepeoplesChamp> place number 48",
"<+TSM-ThepeoplesChamp> im gona post the truths \ <+TSM-ThepeoplesChamp> cos people will follow me \ <+TSM-ThepeoplesChamp> until the day of my death \ <+TSM-ThepeoplesChamp> like superman",
"<@TSM-ThepeoplesChamp> we are both in the top of heaven \ <@TSM-ThepeoplesChamp> cos we are legends \ <@TSM-ThepeoplesChamp> hes in the floor dancing with the fucking worms",
"(+TSM-ThepeoplesChamp) shes my fan \ (+TSM-ThepeoplesChamp) youre jealous \ (+Rachela) Now ignoring TSM-ThepeoplesChamp \ (+TSM-ThepeoplesChamp) you made me lost a female fan \ (+TSM-ThepeoplesChamp) you piece of shit \ (+TSM-ThepeoplesChamp) disgusting acne asshole",
"<+TSM-ThepeoplesChamp> i got followers \ <+TSM-ThepeoplesChamp> the day i get out of irc \ <+TSM-ThepeoplesChamp> irc dies",
"<+TSM-ThepeoplesChamp> im in the wikipedia \ <+TSM-ThepeoplesChamp> im one of the biggest celebrities of this year",
"<+TSM-ThepeoplesChamp> dr dre? \ <+TSM-ThepeoplesChamp> i interviewed him once for my radio show hes a very natural person a good man \ <+TSM-ThepeoplesChamp> he got 3 kids",
"* ChanServ sets mode: -v+b wafk|baked *!*@WingLeSS.user \ * wafk|baked was kicked by ChanServ ((ABot) Repeat flood, 1 min ban.) \ <+TSM-LatinoLegend> hahah \ <@suga|51> wow TSM \ <@suga|51> dont use ur hack console here \ <+TSM-LatinoLegend> the fucker messed with me \ <+TSM-LatinoLegend> im teaching him a lesson",
"<+TSM-LatinoLegend> a hacker is my friend \ <+TSM-LatinoLegend> he knows all the codes of mirc \ <+TSM-LatinoLegend> thats why i get unbaned always in speedpug",
"* KingOfEthiopia was kicked by suga|TSM (SPAM) \ <+TSM-Mexicoschampion> i kicked him \ <+TSM-Mexicoschampion> with my console \ <+TSM-Mexicoschampion> !kick ethipopian \ * KingOfEthiopia was kicked by suga|TSM (TSM HACK CONSOLE) \ <+TSM-Mexicoschampion> dont ever mess with me \ <+TSM-Mexicoschampion> worm \ <+TSM-Mexicoschampion> you get it?",
"<+TSM-THEKING> alt f4 closes the MIRC \ <+TSM-THEKING> i study computers \ <+TSM-THEKING> for 3 years in university",
"<+TSM-ThepeoplesChamp> anti tweak alert whata fuck is that man is kicking me \ <+TSM-ThepeoplesChamp> mintek put me a tramp \ <+TSM-ThepeoplesChamp> the eagle will follow my way as the freedom will find the real heroe \ <+TSM-ThepeoplesChamp> im going strong againts the rivers",
"[23:08:29] [TSM-GOD]: not yet friend im bloging after my meals",
"<+TSM-LatinoLegend> your momy says hello since the deep lungs of hell you fucking weirdo scumbag",
"<+TSM-LatinoLegend> flux true has rat face \ <+TSM-LatinoLegend> he got face textures like a rat",
"<+TSM-Mexicoschampion> you fucking diarrea shit face \ <+TSM-Mexicoschampion> dont mess with me",
"<+soifon> well im not realyl picking the same source of comedy from him than what u guys are getting \ <+TSM-Mexicoschampion> comedy? \ <+TSM-Mexicoschampion> your life is a comedy \ <+TSM-Mexicoschampion> fucking sad nerd clown",
"<+TSM-Mexicoschampion> i beat you dont even know how to talk a girl \ <+TSM-Mexicoschampion> with your big balls of acne \ <+TSM-Mexicoschampion> and your stupid retarded glasses \ <+TSM-Mexicoschampion> you wear brasses too \ <+TSM-Mexicoschampion> fucking disgusting \ <+TSM-Mexicoschampion> il spit my salive into your face youre pathetic",
"<+KingOfEthiopia> u need to take a break from your race. \ <+TSM-Mexicoschampion> whats a race \ <+KingOfEthiopia> u know \ <+TSM-Mexicoschampion> racing? \ <+KingOfEthiopia> u know \ <+TSM-Mexicoschampion> race cars \ <+KingOfEthiopia> u know \ <+TSM-Mexicoschampion> you shut up",
"<+TSM-Mexicoschampion> HAVE FUN of your mom bitch asshole",
"<+TSM-Mexicoschampion> disgusting psycho pathetic i bet you live alone in shithole with lot of old pizza boxes and rotten hamburgerses",
"<+TSM-Mexicoschampion> i feel compasive today \ <+TSM-Mexicoschampion> dont wana make you cry \ <+TSM-Mexicoschampion> punk",
"<+TSM-ThepeoplesChamp> youre fucking with me arctopus \ <+TSM-ThepeoplesChamp> wana troubles?",
"<+TSM-ThepeoplesChamp> ep show your real pic \ <+TSM-ThepeoplesChamp> fat mother fucker \ <+TSM-ThepeoplesChamp> body fat ball \ <+eP|> brb reboot \ * +eP| (evilpriest@Evil_Priest.user) Quit (Signed off) \ <+TSM-ThepeoplesChamp> is he muscular?",
"<+TSM-ThepeoplesChamp> il teach you some modals \ <+TSM-ThepeoplesChamp> fucking bastard",
" <+newb> i am suggesting you are good at putting your hands on long thick things \ <+TSM-ThepeoplesChamp> like your mom? \ <+newb> like penises \ <+TSM-ThepeoplesChamp> like the penises of your mom",
"<+TSM-ThepeoplesChamp> suga you got the proves friend \ <+TSM-ThepeoplesChamp> lets berry this scum in the worms \ <+TSM-ThepeoplesChamp> only the worst scum in planet do that things",
"<+TSM-ThepeoplesChamp> i think this freak \ <+TSM-ThepeoplesChamp> is just jealous cos im a sucsesfull person \ <+TSM-ThepeoplesChamp> and hes not even well know by his parents \ <+TSM-ThepeoplesChamp> no lifer social rejected",
"<+TSM-ThepeoplesChamp> what are you doing reading all the day \ <+TSM-ThepeoplesChamp> the fucking mirc \ <+TSM-ThepeoplesChamp> watching my mouth moving and then \ <+TSM-ThepeoplesChamp> spiting your venenus poison",
"<+afk> http://img707.imageshack.us/i/swb.jpg/ \ <+TSM-ThepeoplesChamp> you need a cut your hair \ <+TSM-ThepeoplesChamp> animal hair \ <+TSM-ThepeoplesChamp> and the sweater looks like \ <+TSM-ThepeoplesChamp> your grandmomka \ <+TSM-ThepeoplesChamp> make it for you",
"<+Lenneth|^> seinfeld looks like a cool dude \ <+TSM-ThepeoplesChamp> wow \ <+TSM-ThepeoplesChamp> i dont wana imagine how ugly \ <+TSM-ThepeoplesChamp> he looks to think \ <+TSM-ThepeoplesChamp> seinfield looks cool \ <+TSM-ThepeoplesChamp> lineth must look like the scarriest weirdo in the town",
"<+TSM-ThepeoplesChamp> your muscles gives me repulsion \ <+TSM-ThepeoplesChamp> they looks must like tumours",
"<+TSM-ThepeoplesChamp> im gona clean the macdonals shits with his faces",
"<@TSM-ThepeoplesChamp> im gona fuck you so hard now \ <@TSM-ThepeoplesChamp> until your weight goes down \ <@TSM-ThepeoplesChamp> and stop beign a nerdy fatty guy youre now",
"<@TSM-ThepeoplesChamp> fat pancakes \ <@TSM-ThepeoplesChamp> i got tthis bitch \ <@TSM-ThepeoplesChamp> down in the floor",
"<+TSM-ThepeoplesChamp> youre a fucking fatto \ <+TSM-ThepeoplesChamp> il throw your punches to your body fat mass until you fall",
"<+TSM-ThepeoplesChamp> hey fucking disgusting mocosus blunts in ts \ <+TSM-ThepeoplesChamp> shut up \ <+TSM-ThepeoplesChamp> youre always sorning your ugly nouses in the mic",
"<+KingKilla> r bug on server i r not git shox rifle \ <+KingKilla> r jiz gota throw lil buble up dur \ <+TSM-ThepeoplesChamp> i dont understand the english of this dude",
"<+TSM-Mexicoschampion> i was police officer i had the drug reports",
"<@TSM-ThepeoplesChamp> i work for 3 magazines \ <@TSM-ThepeoplesChamp> and got my own radio show \ <@TSM-ThepeoplesChamp> i was making my own political team but gets fucked up \ <@TSM-ThepeoplesChamp> after the mexican elections",
"<@TSM-ThepeoplesChamp> i worked before in the mexican jungles \ <@TSM-ThepeoplesChamp> in the radio \ <@TSM-ThepeoplesChamp> like 4.000 persons were with me",
"<+TSM-ThepeoplesChamp> well america is the most fat country \ <+TSM-ThepeoplesChamp> im a teacher asshole",
"<+TSM-Mexicoschampion> i prepare an special sexiestman sauce for sushi im gona upload",
"<+TSM-ThepeoplesChamp> the kitchen is good for cock the greatest recetes",
"<+THEREALSEXIESTMAN> pearl harbor got no war \<+THEREALSEXIESTMAN> stupid love shit story \<+THEREALSEXIESTMAN> and japanese people wins that war \<+THEREALSEXIESTMAN> not the americans",
"<Imp> u guys got like 10x the action of speedpug \ <SEXIESTMANAUSENTE> im gona punch you",
"<REALSEXIESTMAN> i play foootball so i know a lot about teamwork",
"<+REALSEXIESTMAN> stupid fat pie eater \<+REALSEXIESTMAN> you cant even put your hands up cos youre so fat",
"<+REALSEXIESTMAN> i was downloading the movie dragon <+REALSEXIESTMAN> the history of bruce lee \<+REALSEXIESTMAN> from ares \<+REALSEXIESTMAN> and when the download finished \<+REALSEXIESTMAN> i play it and was a porno shit movie",
"<+REALSEXIESTMAN> torrent is nerd i never use it \<+REALSEXIESTMAN> too much configuration crap \<+REALSEXIESTMAN> i already download 2 movies from ares\ <+REALSEXIESTMAN> funhouse <+REALSEXIESTMAN> and predator 1",
"<+TSM-KIngOfLatinos> dont suck my dick anymore \ <+TSM-KIngOfLatinos> go find another dick",
"<TSM-LatinoLegend> its the pic of gays i knew it asshole psycho rotten meat sandguiche",
"<+TSM-KIngOfLatinos> i won \ <+TSM-KIngOfLatinos> but my stomach \ <+TSM-KIngOfLatinos> hurts so bad \<+TSM-KIngOfLatinos> so i let the kid have the lead",
"<+REALSEXIESTMAN> egg licker \<+REALSEXIESTMAN> of the americans \<+REALSEXIESTMAN> fucking asshole \<+REALSEXIESTMAN> i will teach you a lesson \<+REALSEXIESTMAN> im gettin bored \<+REALSEXIESTMAN> .leave",
"<+REALSEXIESTMAN> sure im bad i make the 80%of caps of my team on any speepug game dude \ <+REALSEXIESTMAN> im a good player \ <+REALSEXIESTMAN> respect me bitches",
"<+TSM-GOD> Sorry, but you have to pay me to give you an interview",
"<+MHAD`nomic> YOU STUPID FUCKING NIGS JOIN NOW \ <+REALSEXIESTMAN> WHY HE IS USING BIG LETTERS",
"TSM: TSM SHIRT IS CHICK AND LOOKS NICE IN EVERYONE WHO WANTS TO BE A WINNER. \ You can deposit the money here: Bank-Banco: HSBC Account number- Numero de cuenta: 6181361917",
"<+REALSEXIESTMAN> make a photoshop of your nasty body \<+REALSEXIESTMAN> small man with no life \<+REALSEXIESTMAN> ugly smile \<+REALSEXIESTMAN> you cant kiss a girl \<+REALSEXIESTMAN> the smile of sober is like blades thats cos nobody wana kiss him",
"<+REALSEXIESTMAN> you must be are on fire \<+REALSEXIESTMAN> cos i show to the world \<+REALSEXIESTMAN> how fucking ugly youre",
"<TSM-LEGENDA> hello friend you see they add my famous quotes of irc \ <TSM-LEGENDA> to channel dedecatid to only me with all of my followers \ <nfrs> yes i saw, mr popular *shaking hands* \ <TSM-LEGENDA> *friends hugh* \ <TSM-LEGENDA> yes a channel filled with scum worshipping me and i even have real ops",
"(@TSM-LEGENDA) i have been in UTV already like 100 times, counting my pugs and official matches",
"<TSM-LEGENDA> i fix my pc \ <nfrs> what was wrong with it \ <TSM-LEGENDA> the ventilators \ <TSM-LEGENDA> were stucked with scum",
"(@TSM-LEGENDA) il piss my shit in all the fake logs who do it to be famous with my name",
"<@TSM-LEGENDA> wow everything i say you quote it, somebody needs to get a life",
"<+TSM-GOD> sounds as to me friend that this nigger want a troubles",
"<TSMChampion> who cares about IQ when a nerd with high IQ cant live a day in the streets and everybody punches him in school",
"<@TSM-LEGENDA> if you gona add what i say add only the smart ones, where i teach you about the game of life not about stupid videogames",
"<TSMChampion> But sorry kid girls like atlethes like me, not stupid animalnerd lovers like you. By the way your sister is hot man i want her MSN to make a webcam show. I wait your answers.",
"<TSMChampion> my dick got more muscles than all your body",
"<TSMChampion> you touches yourself watching my pshycally perfection",
"<TSMChampion> go jerk off with your freaking animals, you PSYCHO fenomenous body disgusting pale face",
"<TSMChampion> i make you and i can destroy you, in other words youre like a poop that i need to throw down in the bathroom",
"<TSMChampion> I have lived in the streets a fucking childo like you will never bring me down, not even with a knife a shootgun or a missiles weapon.",
"<TSMChampion> SK gaming is in negosiations with me for a contract.",
"<TSMChampion> i was born to bring down all the quests and hard test in life.",
"<TSMChampion> youre fucking girly and skinny in a real street fight il take you down with one single touch",
"<TSMChampion> you looks like a death cadaver, you need look at my healthy recetes if you wana live some more time ANOREXIC GUY",
"<+REALSEXIESTMAN> youre ugly dude \ <+REALSEXIESTMAN> dont blame \ <+REALSEXIESTMAN> me \ <+REALSEXIESTMAN> cos of that \ <+REALSEXIESTMAN> i dont have the fault you look like a fucking monster",
"<TSMChampion> gona give you my personal adress so i can show you my modeling pics while you touches",
"<+REALSEXIESTMAN> i show me on cam and girls pay me",
"<+REALSEXIESTMAN> he thinks im ugly like you sober but when he see me he go to make some more work out",
"<TSMChampion> you can call me mister 50 efficiency",
"<+REALSEXIESTMAN> i know like im not a nerd like theyre \ <+REALSEXIESTMAN> are jelous \ <+REALSEXIESTMAN> the same guy that kick theyr asses on school \ <+REALSEXIESTMAN> come here and kiss theyr asses on videogames \ <+REALSEXIESTMAN> thats me",
"<+REALSEXIESTMAN> storm is falling on mexico \ <+REALSEXIESTMAN> storms gibes me lag",
"<+melissa7> till this day i cant believe sexiest is not banned \ <+REALSEXIESTMAN> you must be are banned for pretend by a female \ <+REALSEXIESTMAN> when youre a old fat man",
"<+[CAMBODIA]TaTa_SnOrLaCk> wha is boost? <+TSM-GOD> boost is a kind of bot <+TSM-GOD> who gives velocity <+TSM-GOD> to your player",
"<+WoW-TSM> i drinking some whiskey (+WoW-TSM) for celebrate my victory \ <+WoW-TSM> johnny walker \ <+WoW-TSM> blue lavel \ <+WoW-TSM> i like toplay clasical music \ <+WoW-TSM> and drink fine whiskey \ <+WoW-TSM> after a victory",
"<+TSM-ThepeoplesChamp> both you and me are legends in this game gogeta you follow your path \ <+TSM-ThepeoplesChamp> il follow mine",
"<+TSM-ThepeoplesChamp> i reinvented the combo in movement \ <+TSM-ThepeoplesChamp> jumping and combo",
"<TSM-Mexicoschampion> i take my gaming serios when i play i focus on my enemys and nothing but the enemy",
"<+TSM-ThepeoplesChamp> i got a old \ <+TSM-ThepeoplesChamp> LP from rocky 1 2 and 3 \ <+TSM-ThepeoplesChamp> sometimes i put it when i play this game \ <+||speedemon||> EYE OF THE TIGER? \ <+TSM-ThepeoplesChamp> yes and hearts on fire",
"<Joe> 72 weeks ago [00:52] <MISTERSEXIESTMAN> thats almost a year [00:53] <Joe> how many weeks are in a year? [00:53] <MISTERSEXIESTMAN> like 70 [00:54] <MISTERSEXIESTMAN> whata [00:54] <MISTERSEXIESTMAN> 42 weeks in a year [00:55] <Joe> wow [00:55] <MISTERSEXIESTMAN> what [15:02] <BRONCOS4LIFE> thats hilarious [15:03] <MHAD> isnt there 36? [15:03] <Joe> :|",
"<FERNANDO> heelo <TSM-GOD> hello <FERNANDO> wat u doin <TSM-GOD> watching my muscles at the mirror <TSM-GOD> what you doing",
"[05:18] <+TSM-GOD> i ride yoshi always \ [05:18] <+TSM-GOD> in mario kart ds \ [05:18] <+TSM-GOD> i like that caracter is very fast \ [05:18] <+TSM-GOD> i got some real yoshis of toys \ [05:18] <+minteK> Do they get along with your homer simpson chair?",
"<TSM> beans are one of the most great aliments",
"[6:52:32] <TSM-GOD> your a discrase to your country and will never be a real mexican like me from the ghetos",
"[12:21:35] <TSM-GOD> girls at my school know im a true champ when they read it in my blog",
"<+WoW-TSM> in the old times magic was better than weapons \ <+WoW-TSM> but they baned magic from all across europe and when rasputin dies magic dies, now magic is just used by dorks",
"<+WoW-TSM> Since im one of the few rich persons in my Town, everybody wana come to my house and uses my XBOX, too bad i lock the doors of my big house and start the adventure by myself.",
"<+WoW-TSM> the anals is like a history book like historial of matches",
"[12:45:52] <WoW-TSM> yeah i let that match chicken beat me cos hes only weapon was that fucking @ in his nickname",
"[12:24] <+WoW-TSM> the cientific persons says that you need at least misticate 100 times your aliments for good digestion",
"<WoW-TSM> you dont belive in magic cos you got no soul nfrs <WoW-TSM> i wish to have rasputin magic books for make you an spell so you can stop be so gay",
"<+WoW-TSM> no fags in a mexican macho family of atlethes",
"<+WoW-TSM> you cant say im wrong when you see those kind of cocksucker like chriss angel making rich with his magic",
"<+WoW-TSM> i have give master classses of guitar in the ts of unrealtournament",
"<+WoW-TSM> but the statics are contundent",
"<+TSM-GOD> this planet needs to be restarted <+TSM-GOD> cos is fucked up <+TSM-GOD> fucked of cos people like you who is jealous of me <+TSM-GOD> people who sits in the chair all the day and never make something about life just watch pornkid <+TSM-GOD> and jerkoff while <+TSM-GOD> smokes <+TSM-GOD> and plays ut",
"<+TSM-GOD> you will be in the punishment chair if you touch me",
"<+TSM-GOD> i have always i dream <+TSM-GOD> if to make my own school and prepare people to become winners at what they like to do <+TSM-GOD> by example <+TSM-GOD> 4 months with me il change your life tom <+TSM-GOD> make you an atlethe",
"<+TSM-GOD> cherrios cant be degustated for the stomach , the little things get stucked in your stomach forever",
"<+lkemas> TSM have you ever been in space | <+TSM-ThepeoplesChamp> yeah man that was like 3 years ago | <@Area51|flux> was it cold up there? | <+TSM-ThepeoplesChamp> whata fool | <+TSM-ThepeoplesChamp> the space cant be cold | <+TSM-ThepeoplesChamp> space dont even got temperature",
"<+TSM-KINGOF1VS1> canadians fucking rocks, poor americans only thing they got is spiderman and baseball",
"<+DerrickRose> remember the alamo sexi \ <+TSM-KINGOF1VS1> yes \ <+TSM-KINGOF1VS1> the alamo \ <+TSM-KINGOF1VS1> is a fucking fake history \ <+eP|> REMEMBER THE FUCKING ALAMO",
"<+TSM-LatinoLegend> fucking retarded teacher of thiefs",
"-WoW-TSM: owned with fflag cannonball from the space",
"<+TSM-ThepeoplesChamp> you need to cut the envolture of the cucumber \ <+TSM-ThepeoplesChamp> rip the cucumber from the middle \ <+TSM-ThepeoplesChamp> you extract the bones of the cucumber \ <+TSM-ThepeoplesChamp> with the spon you take the bones of the cucumber \ <+TSM-ThepeoplesChamp> and then cut it down in pieces \ <+TSM-ThepeoplesChamp> add all the pieces of cucumber to the liquiefy machine",
"<TSMChampion> Womans from all the cultures and countrys have been in my bed ... i just missing a finlandece what do you say?",
"<TSMChampion> I show the evidence to a girls, not a fucking homo cadaver like you... your so thin i can confuse you with a girl if you put a wig and you make up your anemia face. And i know jessica alba, we are both worldwide stars i have meet it in partys, we dont talk too much hes realy not my type.",
"<TSMChampion> Stop the anorexia man and maybe i can help you, by watching my mango videos is the first step to become a winner.",
"<TSMChampion> i know 3 things about you Mr... 1.- You got a lot of free time. 2.- You hormones start to dance when i post a coment for you cos you feel excited 3.-Youre like the fucking media and the paparazzis that follows me everyday, and thats fucking anoying.",
"<DASEXIESTMAN> MAYBE \ <DASEXIESTMAN> IM A LITTLE FAT \ <DASEXIESTMAN> SOME ACNE \ <DASEXIESTMAN> NO SLEEP ON YEARS \ <DASEXIESTMAN> A VERY DIRTY MAN \ <DASEXIESTMAN> NOT TAKING BATS",
"<TSMBlog> Yo yo to all my followers i introduce you my new little simpson`s couch. I just buy it for 35 dollars, very confortable and good to relax when youre resting the muscles of a hard day of training.",
"<TSMBlog> Some guy from speedpug called Kingkilla send me this nasty disturbing pic ... i think this guy is a fucking loser depravated that just want some attention showing his ugly dick on the plate.",
"<TSMChampion> Well im so famous that youre in Finland and im Mexicos so my name is running in the skies above all the world. The other day 2000 people were watching my game in the TV. And the pic thing, yeah im gona send to pic into your channel so you can put my pic as a poster into your bedroom and you can have water dreams.",
"<+WoW-TSM> follow my techniques for get laid and you will wake up with 4 girls in that bed \ <+WoW-TSM> my record is like 22",
"<@suga|51> http://album.pnt.net/album/album/images/l/larathiel01.jpg \<@suga|51> TSM man you think you could take this guy in a street fight? \<@TSM-ThepeoplesChamp> he looks very strong \<@TSM-ThepeoplesChamp> and wild as an animal \<@TSM-ThepeoplesChamp> but i will owned him with intelligence \<@TSM-ThepeoplesChamp> i can move so fast he will decapitated his llama and then i punch him in the nouse very hard",
"<+WoW-TSM> *serving fine jonny walker blue label and celebrating*",
"<+WoW-TSM> poor? <+WoW-TSM> i have an xbox 360 <+WoW-TSM> you fucking dumbshit <+WoW-TSM> only the richiest person in mexico got xbox 360",
"<+WoW-TSM> fuck the north of mexico, i leave in the south <+WoW-TSM> where the people is smartert",
"<+Seinfeld`Curse> spic tsm you talk a lot of shit <+Seinfeld`Curse> for a poor person <+WoW-TSM> poor? <+WoW-TSM> i have an xbox 360",
"<nfrs> wanna play a tdm pug to remember? / <TSM-GOD> hello man / <TSM-GOD> im in spic pug sorry man",
"<TSM-GOD> a football player cant play 2 official games per day / <TSM-GOD> ut is like an sport / <TSM-GOD> and i need rest",
"[8:07pm]«+ TSM-GOD » my friend told me you lied about mortal kombat was based in a true history",
"<+THESEXIESTMEXICAN> there is no turning back for a champion, i take my desition and the desition is clear im trying to reach more horizonts",
"<+THESEXIESTMEXICAN> i have a little house in the woods, was full of spider and the grass was big",
"<+THESEXIESTMEXICAN> yeah man, i was in vacations in the forest not more fucking videogames just me and the nature",
"<+THESEXIESTMEXICAN> why you let your ugly lifes get rotten in this place? XBOX LIVE IS WAITINGH FOR YOU",
"<+THESEXIESTMEXICAN> this isnt my past, was just a trip into the journey... i was famous since lots of yearrs after this",
"-02:31:56- (+THESEXIESTMEXICAN) die with the swords to the bettrayers",
"(TeamXlink) Its done installing, do you still want to play? / (THESEXIESTMEXICAN) ok TEAM",
"<@TSMPEOPLECHAMP> il send my mexican people to fuck you in the ass",
"<@TSMPEOPLECHAMP> whata fucking pussy youre trying look bad in a pc",
"<@TSMPEOPLECHAMP> you havent a single book in your life",
"<%TSMPEOPLECHAMP> farewell to followers, until the moon becomes shine again i will comeback",
"<+THESEXIESTMEXICAN> i make more points than you <+THESEXIESTMEXICAN> i have the screen",
"<+THESEXIESTMEXICAN> when you buy some balls talk to me again you make my stomach hurts",
"(+THESEXIESTMEXICAN) i have a gang of guys that follow me in real life / -23:01:19- (+THESEXIESTMEXICAN) who go to the gym together and they watch me play ut",
"<+THESEXIESTMEXICAN> isnt a bad thing shower with another guy when you know youre totally straigh",
"<+THESEXIESTMEXICAN> must be are a negro name",
"<+THESEXIESTMEXICAN> lick my cocodrile boots",
"<TSM> He's a noob i make a spree on him again",
"<+THESEXIESTMEXICAN> suck my dick nixon, youre jealouss cos im the most respected and famous player in this game",
"<+THESEXIESTMEXICAN> you live in the excuses, you cant play me cos youre eating, you smoke all the day cos you have troubles, you dont excersice yourself cos you have lazzy",
"<+THESEXIESTMEXICAN> i fight with those niggers and im the captain of my own soccer team",
"<+THESEXIESTMEXICAN> we got the most retarded player in ut <+THESEXIESTMEXICAN> blunts and his ugly mocus in ts",
"<+THESEXIESTMEXICAN> i just come here cos my 360 disconects again",
"<TSM> I meet the fake santa but not the real one <TSM> hes death already but existed in the medieval times",
"<TSM> dont put dirty in the name of christmas friend",
"<TSM> I have bath please wait 30 seconds",
"<+TSM-LEGEND> canada is the hat of america",
"<+TSM-LEGEND> i feel pleasure when i won a match, i feel pleasure when i got all the females is the same sensation",
"<+TSM-LEGEND> you dont know about that cos all the day youre in the fucking computer <+TSM-LEGEND> modeling your ugly bodyfat ball",
"<+TSM-LEGEND> canada got not even history <+TSM-LEGEND> mexico got like 10000 books of pure mexican history <+TSM-LEGEND> i have read all about canada in 3 single books <+TSM-LEGEND> fucking boring nation",
"<+TSM-LEGEND> mexico was america <+TSM-LEGEND> but america steal all our lands <+TSM-LEGEND> they buy it for the right price acording some stupid thiefts",
"<+TSM-LEGEND> i dont need money i can buy your mom if i want",
"<+TSM-LEGEND> i have cross all the borders i have travel to japan, rusia, france",
"<TSM-GOD> youre depravated <TSM-GOD> thats why youre the porno pig <nfrs> depravated of what <TSM-GOD> homosexuality",
"<+TSM-LEGEND> if you want real train come here to mexico, sell your fucking pc and nerd videogames i will make you a man of good",
"<+TSM-LEGEND> you spend to much time sitting your fat asshole in that chair <+TSM-LEGEND> you need to run in the streets <+TSM-LEGEND> or the mountains <+TSM-LEGEND> travels and stay away from the monitors <+TSM-LEGEND> you need meet nature again <+TSM-LEGEND> cos man is nothing without nature",
"<+TSM-LEGEND> indians from america becomes cowboys when they evolved",
"<+TSM-LEGEND> i have a collection of 7000 movies in my basement",
"<+TSM-LEGEND-> you smells of sweet lavender",
"<+TSM-LEGEND-> nfrs doesnt say that <+TSM-LEGEND-> hes my friend <+TSM-LEGEND-> my right hand <+TSM-LEGEND-> like the goodfather has his right hand <+TSM-LEGEND-> i got my second hand too",
"<+TSM-LEGEND-> lots of people pay me for sex <+SC`QL> really? <+SC`QL> so gay men pay you? <+TSM-LEGEND-> they offered me money but i say no <+TSM-LEGEND-> my perfection is only for the female",
"(+TSM-LEGEND-) do uyou know / (+TSM-LEGEND-) justin tv / (+TSM-LEGEND-) i cum at night, wwatching a very hot girl after that i go to old man channels to have a chat",
"<%snkypooooo> tsm was tired from boxing <%snkypooooo> hands are weak <%snkypooooo> thats why <+TSM-LEGEND-> and i was jerking friend <+TSM-LEGEND-> hands were dirty to touch well the computer",
"<+TSM-LEGEND-> everybody feels inferior when i show my muscles to the people",
"<+TSM-LEGEND-> the pug is like you calla boxer to a fight when hes having sex at night",
"<+TSM-LEGEND-> why you show that shit no one cares nooba <+Ultranovaa|^> i make money <+TSM-LEGEND-> you make less money than me modeling in all the websites",
"<+TSM-LEGEND-> here are no niggers who stole your money <+TSM-LEGEND-> like in NY <+TSM-LEGEND-> when i go to vacations there <+TSM-LEGEND-> 2 niggers stole all my packages <+TSM-LEGEND-> i was in the taxi <+TSM-LEGEND-> and when i comeback taxi driver say 2 niggers stole all my goods",
"<+TSMPEOPLECHAMP> i was elected for candidate of the water years ago but i give my place to other guy",
"<+TSM-SUPERLASTPICK> those stupid negros are retard man, last time i meet a nigger he has dignity now they lost all they roots trying to make fun the white person",
"<+TSM-SUPERLASTPICK> duck is expensive and good with a fine cup of blue label <+TSM-SUPERLASTPICK> duck is class you dumbass bitch",
"<+TSMPEOPLECHAMP> .list <@ABot> ««« UT99.TDM.Weapons «» Letter: D «» Puglist (2/6) «» 1) TSMPEOPLECHAMP 2) Ultrawawa|^ «» 4 spots remaining »»» <+TSMPEOPLECHAMP> .join",
"[01:17:46:AM] <+TSMPEOPLECHAMP> i bet he masturbates with all the ss he takes about me",
"[01:46:31:AM] <+TSMPEOPLECHAMP> girls dont have dick <+TSMPEOPLECHAMP> have vagina <+TSMPEOPLECHAMP> like nixon who has stinky vagina",
"<+SKGaming-TSM> in mexico we dont like drugs we just send them to america for the right price",
"<+SKGaming-TSM> im sk member now <+SKGaming-TSM> what are you? <+SKGaming-TSM> oh yeah sure i forget youre an stupid fatso who play since 10 years and still sucks dick at ut fucking no lifer <+SKGaming-TSM> fucking dumbass try to fuck up my christmas times",
"<+TSM-RETIRED> 1 vs 1 we can use the quake live detective to find us",
"<TSM-RETIRED> i have never say a single lie in my life",
"<+TSM-RETIRED> i know youre happy, you can stay safe now in your computers cyberworld without a man that tells you the truth like your mother never does it",
"<+TSM-RETIRED> you ask in the streets whos echo and the people spit at you, you ask in everyplace whos sexiestman and the péople knows who i am at least in mexico",
"(+TSM-RETIRED) desilucional tom, will never learn .. him and his life is stucked just like this game",
"-21:14:48- (+TSM-RETIRED) thats all for now / -21:14:53- (+echo) pay him fo more",
"(+TSM-RETIRED) ram when you retire not even a fly will cry, if i leave this game lots of people gona do crazy things",
"<+TSM-RETIRED> I just finished play quake arena <+TSM-RETIRED> the time go sofast <+TSM-RETIRED> unbelieablkebe",
"<TSM-RETIRED> my cum will fill your guts stupid scared chicken",
"<TSM-RETIRED> i just challenge you and chickens out, in 7 months i become better than you playing 10 years",
"<TSM-RETIRED> are you angry stupid geeko, lets see your rage in 1 vs 1 duel and show me youre not so pathetic loser",
"<TSM-RETIRED> hahahaha, youre a nerdo <TSM-RETIRED> im an atlethe, a musician <TSM-RETIRED> even the most fucking famous person in videogames <TSM-RETIRED> how can a nerd asshole like you <TSM-RETIRED> talk crap to a winner like me",
"<TSM-RETIRED> your gf will lick my perfect mexican abs",
"<TSM-RETIRED> my muscles are sexier than your fucking big nerdo glasses",
"<TSM-RETIRED> at 12 am, crying like a porky bitch just because youre too fucking loser to play me 1 vs 1 duel",
"<TSM-RETIRED> mexico is a paradise <TSM-RETIRED> americans come here to vacation in my paradise",
"<TSM-RETIRED> mexico is the biggest city in the world <TSM-RETIRED> even sinatra says is the best city to live for",
"<TSM-RETIRED> did you put your dick on, seems like you have some balls now unless youre saying excuses again",
"<TSM-RETIRED> stupid dumb american / <TSM-RETIRED> seems like my words go straight into your asshole",
"<+TSM-RETIRED> ey nixon look at what i buy for you for christmas http://thesexiestman.blogspot.com/2010/12/tsm-christmas-presents.html",
"<+TSM-RETIRED> tom did you see your present for christmas you must share it with nixon one week and one week ok",
"(+TSM-RETIRED) everybody adds me and say wow you play ut99 right / (+TSM-RETIRED) and i answeer yes / (+TSM-RETIRED) and they want to be teached by me",
"(+TSM-RETIRED) im the honour of the jungle, american dumbass you will never live not even 2 days in the jungle",
"(+TSM-RETIRED) you live of the lies, all you say was ripped of from cocodrile hunter movies",
"(+TSM-RETIRED) youre angry cos your christmas was shit and the food will rotten",
"+TSM-RETIRED) im the only one who can see what the animals are really saying how can you live in jungle when youre here all the day celevrating new year and christmas in the fucking mirc channels?",
"(+TSM-RETIRED) youre making my pacience angry i willkick you soon",
"<+TSM-RETIRED> i have fuck up by the ass <+TSM-RETIRED> so many spicos",
"(+TSM-RETIRED) i just dont make you cry cos we are in chirstmas times / (+TSM-RETIRED) if wasent in christmas i will make you my bitch",
"TSM-RETIRED when the night meets the midnite moon i will comeback",
"<+THESEXIESTMAN> i have spread my words of freedom all over the places",
"<+THESEXIESTMAN> xboxis fine but i got the money to buy all the laptops i want and play ut again i specially pick this custom laptop with the keys i want and modifications to be the best once again <+nfrs> tsm does it use homer simpson keys? <+THESEXIESTMAN> the shock key got the shock rifle weapon cartoon in the key so i know thats not a letter thats the weapon i want to pick",
"(+THEZEXIESTMAN) and i will crush your face in real person for disrispect me / (+THEZEXIESTMAN) if your father didnt teach you modals / (+THEZEXIESTMAN) i will do",
"(+THEZEXIESTMAN) honor is all what a man haves, and i can see your father dont wanted to invert 10 minutes with u to talk about honor courage and what a men is all about",
"<+THEZEXIESTMAN> hes angry dont ever make a spic hacker angry",
"<+THEZEXIESTMAN> you cant even have a real gf in your life how a loser like you can beat a winner like me",
"<+THEZEXIESTMAN> i have weapons for mouses if someone wants to get a piece of the pie so noone can touch me",
"<THEZEXIESTMAN> i can beat gorillaz and cocodriles while i lived in jungle",
"<THEZEXIESTMAN> i have won more money in 1 month teaching people ut than you won in all your life at your cheessbuger macdonals works",
"<THEZEXIESTMAN> i never meet sucha stupid canadian disrispectful nigger ranch fuck",
"<THEZEXIESTMAN> cybherg <THEZEXIESTMAN> i want you to be friend <THEZEXIESTMAN> want a cup of johnny walker blue label",
"(+THEZEXIESTMAN) i think is fair to respect one of the best players even when hes a stupid psycho thieft eyes of fish",
"<+THEZEXIESTMAN> is this clown of poor circus talking to me?",
"(+THEZEXIESTMAN) whats the prize for winning mlut / -22:38:14- (%LaG|Se7eN) your name on the boxes of UT Anthology / -22:38:20- (%LaG|Se7eN) aka, all the UT boxes. / -22:38:33- (+THEZEXIESTMAN) BUT MINtek told me other thing",
"<+THEZEXIESTMAN> ready to take off the dust of the bones with a 1 vs 1 match",
"<+THEZEXIESTMAN> determination, presision and perseverence are the p`s of a winner",
"<+MISTERSEXISMAN> ey <+MISTERSEXISMAN> you there <+MISTERSEXISMAN> ready to play <+MISTERSEXISMAN> dominican garbage ball",
"<+MISTERSEXISMAN> i can smell feel from here <+MISTERSEXISMAN> smeel fear",
"<THEZEXIESTMAN> little perverted i bet he likes to do weird things with his fucking big nouse",
"(+solo) it was a match to remember / (+THEZEXIESTMAN) yes friend like 2 wild creatures in the jungle fighting for honour",
"<+THEZEXIESTMAN> ciro is like a fucking rotten meat stick in the shoes man",
"<+THEZEXIESTMAN> just this fuckig bitch need to treath the legends like legends and not like his fucking sister",
"(+THEZEXIESTMAN) seinfield wana touch my muscles",
"<+THEZEXIESTMAN> my brother is working on a new map called ciros playground <+THEZEXIESTMAN> with lots of tucan birds in a big box",
"<THEZEXIESTMAN> im gona make your shit circus fall stupid fake loser attention freak",
"<THEZEXIESTMAN> im white <THEZEXIESTMAN> i come from mexico and french <THEZEXIESTMAN> face white of a model with french textures and muscles of aztec warrior <THEZEXIESTMAN> perfect package in one person",
"<THEZEXIESTMAN> after this match your will remember me everytime you see your ugly fat potato face in the mirror",
"<nfrs> *toast of high quality fine sandguiches* <THEZEXIESTMAN> fuck man i wish to have a sandguiche in my mouth right now <THEZEXIESTMAN> serrano jam <THEZEXIESTMAN> chesse of sheep <THEZEXIESTMAN> is great friend <THEZEXIESTMAN> and a cup not too much just a little cup of whiskey scotch like a good leprechaunt",
"<+THEZEXIESTMAN> you fucking <+THEZEXIESTMAN> layer bitch <+THEZEXIESTMAN> pepsi freak <+THEZEXIESTMAN> pìg officer",
"<+THEZEXIESTMAN> i make my shits in ciro face man",
"-00:13:10- (+THEZEXIESTMAN) i buy my car playing an ut tournamemnt back in 2004",
"(+THEZEXIESTMAN) im a very tall sexy mexican person who gets pay by females",
"<+THEZEXIESTMAN> lick my strong muscles thiny fuck",
"(+DREW-TANg) tsm do you have any tats / (+THEZEXIESTMAN) whats that / (@{51}ninja-4-L) tattoos / (+THEZEXIESTMAN) yeah man when i was in prision / (+THEZEXIESTMAN) now i delete him with lasers / (@{51}ninja-4-L) how many tattoos tsm / (+THEZEXIESTMAN) not laying like 14 friend / (+THEZEXIESTMAN) time to play the pug / (+THEZEXIESTMAN) *not here*",
"<+THEZEXIESTMAN> too pack shakur <+THEZEXIESTMAN> nwa <+THEZEXIESTMAN> nigggas with attitud so nice man <+THEZEXIESTMAN> hardcore rap not bullshit like today <+THEZEXIESTMAN> fakke niggers are not a threat anymore for the whiteperson <+THEZEXIESTMAN> like a domesticated animal",
"<+THEZEXIESTMAN> i was defeding my basse and some stupid noob prick gets in the way and he falls to the lava",
"<+THEZEXIESTMAN> in mexico we drink cocoes tequila and fresh water of fruits",
"<+THEZEXIESTMAN> no one likes usa only thing too drink is coca cola chessbuger fuck",
"<+MISTERSEXISMAN> stop talking shit like hamster hidding there loser",
"<+MISTERSEXISMAN> il make my shit right into your friendshit",
"<+BallistiC> maybe sly and tsm can go out on a date <+MISTERSEXISMAN> a friends date to the gym <+sLY> *shakes hands* <+MISTERSEXISMAN> *shaking of the hands with great style and strength`*",
"<+THEZEXIESTMAN> nfrs nigger ball of grass",
"(+MISTERSEXISMAN) living in victory we stand together",
"[08:50:06:PM] <MISTERSEXISMAN> feels good when a fucking loser who only thing can do in life is sit his fatasshole in that chair and preteend to be a good player, be racist with other players and worst of all suck at the only thing you try to do in your pathetic empty life",
"<+MISTERSEXISMAN> beating all those racist fucks with my skills <+MISTERSEXISMAN> racist pig go back to your trunck house <+MISTERSEXISMAN> ampenergy youre a redneck sisterfisting hillbilly faggot <+MISTERSEXISMAN> always puting your nouse in my asshole",
"<+THEZEXIESTMAN> whata pork face man the loser wanted to humillate me and gets his medicine well",
"-03:14:10- (THEZEXIESTMAN) we make it again / -03:14:14- (THEZEXIESTMAN) living in victory / -03:14:21- (THEZEXIESTMAN) latinos will raise and beat america",
"<+THEZEXIESTMAN> only a loser can do is talk like a guy who is in the jail and blames everybody or the succes in the chair at the boss officine",
"(+THEZEXIESTMAN) go to play chess at your hamster nerd club at the top of the trees i just play ut",
"<+THEZEXIESTMAN> suaron you retarded piece of shit is like cristiano ronaldo challenges manny paquiao to a penalty shootouts thats not my thing",
"<+THEZEXIESTMAN> goo practice will be much more fun that talk with this loser",
"<+chicken-drunk> what <+chicken-drunk> whats wrong tsm? <+THEZEXIESTMAN> sending me those repulsive pics <+THEZEXIESTMAN> wana see the pic this fucking loser send me <+THEZEXIESTMAN> http://home.comcast.net/~chicken3/tsmsucks.jpg",
"<+THEZEXIESTMAN> dont even try to look like a man right now mister last pick fuck",
"<+THEZEXIESTMAN> youre just a nerdo im an atlethe <+THEZEXIESTMAN> i see this game like an sport you see it like a fucking nerd computer game",
"<detox> <MISTERSEXISMAN> *punching in stomach* <nfrs> is this true <nfrs> *poke poke* <nfrs> mister sex is man <MISTERSEXISMAN> im masturbatingmanleave me alone",
"(+MISTERSEXISMAN) nfrs man yougo everyday with your litle shorts and big hat to delivery letters to all the redneck houses of america friend dont lie",
"<MISTERSEXISMAN> lets together rice our cups and sings our songs",
"<MISTERSEXISMAN> *doing the chicken dance in front of your acne holes little",
"(+MISTERSEXISMAN) not giving publicity a fucking loser wanabe like you not even got the talent for appears in my blog",
"(+MISTERSEXISMAN) scared to play a guy who just comebacks and he talk shit like was a real pro i shut up his asshole",
"<MISTERSEXISMAN> 1 vs 1 wheels chair fuck",
"franky told me that youre laying about the golden medal is beign forged for the winner of mlut",
"<+THEZEXIESTMAN> time to put the sleeping clothes and bed",
"<+MISTERSEXISMAN> respect the legend stupid transexuale",
"<+THEZEXIESTMAN> i mean your biggest problem in life is when your fatso dick gets stuck in the disquetes player of the pc while watching pedofilies porno freak what can you know about life",
"(MISTERSEXISMAN) i will pray for you cos in the final day you will condemnet to damnation",
"<+MISTERSEXISMAN> respect the legend while playing on same time and get the best latin american player of all times, threat me like a bum and a bum you will get",
"<+MISTERSEXISMAN> im the heroe of match and i get pick last and the best frager close combat player",
"<+THEZEXIESTMAN> hes not good hes just the onlydecent runner but the european players of me on my old times beat him without troubles",
"<+THEZEXIESTMAN> someone package me / <+THEZEXIESTMAN> and disconect / <+THEZEXIESTMAN> he package my conection and crashes was that fucking spic who dont want to see meplaying here",
"(+THEZEXIESTMAN) solo is the only one who looks like a fat bean so i dont care spongefriend",
"6:54pm (+MISTERSEXISMAN) my muscles are considered as a weapon by the law",
"2:37pm (+THEZEXIESTMAN) determination, presision and perseverence are the p`s of a winner",
"7:24pm (+THEZEXIESTMAN) my brother is working on a new map called ciros playground 7:24pm (+THEZEXIESTMAN) with lots of tucan birds in a big box",
"(+THEZEXIESTMAN) he picked me before solo (+THEZEXIESTMAN) i muist be are really god (@detox) ur good (+THEZEXIESTMAN) thanks man (+THEZEXIESTMAN) *shakes hand with honour* (@detox) *eats sandguiche* (+THEZEXIESTMAN) tdont say that man",
"<MISTERSEXISMAN> next time i see you talking like that in public channels youre deported",
"<+THEZEXIESTMAN> trying to look like an smart laboratorie hamster look even more pathetic that tom trying to stop the cigarretes",
"<+MISTERSEXISMAN> http://webzoom.freewebs.com/embroiderydesignstore/0%20dora/tucan-tico.jpg <+MISTERSEXISMAN> looks like ciro and his wetback friend indoe",
"<+MISTERSEXISMAN> u think is fun me punching your grassy fat ass",
"<+MISTERSEXISMAN> why give publcitiy a loser wanabe who want attention <+MISTERSEXISMAN> newb do u want me to use my belt on your anus",
"<+MISTERSEXISMAN> il show u the pic of my gf but dont <+MISTERSEXISMAN> say a comment <+MISTERSEXISMAN> [photo of nude man removed]",
"<+MISTERSEXISMAN> CRP youre just a fat tub of nigger shit spicball and his girlfriend is a amazon nigger lover",
"<+THEZEXIESTMAN> sly is fucking hot man",
"<+THEZEXIESTMAN> i have a big party last night with my friens [photo of naked men removed]",
"<+TSM-LatinoLegend> il fuck your mom <+TSM-LatinoLegend> then your sisters <+TSM-LatinoLegend> then il fuck you <+Kaetzchen> my mom is dead <+TSM-LatinoLegend> im gona fuck her grave",
"<THEZEXIESTMAN> in your hood i bet the strong niggers have fun of you <THEZEXIESTMAN> for use twiter and facebook",
"<+THEZEXIESTMAN> have u ever play wii online <+THEZEXIESTMAN> golden eye on wii is good the weapon feels like real <+THEZEXIESTMAN> u control it with movement and mortal pressision <+THEZEXIESTMAN> but my favorite is mario cars with yoshi the cocodrile nothing can stop me",
"<nfrs> lets have a friends practice you taco muncher <THEZEXIESTMAN> im on my laptop watching the waves of the sea going up and down having a nice piña colada and ready for chavez jr fight",
"(+THEZEXIESTMAN) all you guys always want to screw my carrer because i own your asses",
"(+THEZEXIESTMAN) the people and god knows",
"<+THEZEXIESTMAN> waasent so much challenge, he gets on my trap like a rabbit stealing zanahories on the wrong ranch",
"(+THEZEXIESTMAN) like the anals of the history a champion will be always signal as the enemy like Mohuamed ali on his times",
"<+THEZEXIESTMAN> my gamestyle says it all, i improvise like a black person doing street rap and when i need presision i strikes like a perfect bite of an eagle on his enemyes, all the game i just camp at portal and the enemy comes to the trap",
"<+THEZEXIESTMAN> When the people start to scream Ole Ole Ole Oleeee Sexiestman Sexiestmaaan at the stadium gives me all the stamina and oxygen to the head to think smarter my plays and score another W. Thanks",
"(%LaG|Se7eN) yo drew / (%LaG|Se7eN) can you teach me how to dougie? / (%snkypoooooop) i can / (%LaG|Se7eN) werd / (%nfrs) whata nerdos / (%nfrs) tsm taught dougie how to dougie",
"10:32pm (apagon\\) hurry up, panic is going to ban you 10:32pm (apagon\\) if you dont show up 10:33pm (MISTERSEXISMAN) damn that bastard 10:33pm (MISTERSEXISMAN) let me jerk off really quick",
"<Sebastian> hello champion[19:48] <Sebastian> dont say to nobody im sexiestman[19:48] <Sebastian> im behind a mask",
"<+Sebastian> i dont have any money <+Sebastian> for buy ts3",
"(Sebastian) next step how can i authorized my name friend <> (Sebastian) or register <> (Sebastian) im gona play as sebastian until i reach nice skills",
"<+Sebastian> whats aliasing",
"<+Sebastian> im mexican i cant understand english and my computer is too slow for play teamspeak<Sebastian> that nerd thinks all the pcs are born with a ts3",
"<Sebastian> i am feet model do u like feet",
"<Sebastian> Melissa7 you wana lick my abs muscles",
"<+Sebastian> whats the server <@RC> q saloon <@RC> q bleach <@RC> q tsm <+Sebastian> stop playing games with me fool",
"<sebastian> i left the game cos i go to africa to study a new medicines <sebastian> its a new medicie with spider poison i cant talk much about it we are working on it",
"Quote 504: de`mercy was kicked by ChanServ (Repeating is not allowed in this channel) <+Sebastian-Legend> ikick him <+Sebastian-Legend> hack console was used <+Sebastian-Legend> *kb mercy msdos",
"<+kiwi> tsm do u have a microphone <+Sebastian-Legend> yes <+Sebastian-Legend> for microphones fight",
"<+SunnY> i got music playin <+Sebastian-Legend> hes dancing the dance of the nerds",
"<TSM-LEGEND> i got my pijamas right now <TSM-LEGEND> cealvin klains",
"<+Sebastian-Legend> im fine cos i controled all the map and we won <+Sebastian-Legend> cos my strategick <+Sebastian-Legend> for me? <+Sebastian-Legend> racism <+Sebastian-Legend> RACISM",
"<Sebastian-Legend> youre a douchenerdybag of lies",
"12:47am (Sebastian-Legend) i will lick the ass of the jamaiquinas after a night of reggae and yerbs",
"12:51am (Sebastian-Legend) im dancing this song right now friend drinking fine whiskey scotch blue lavel wana join the party http://www.youtube.com/watch?v=xGWlYAzXNj4",
"1:41am (+Sebastian-Legend) hey solo dude get salamanella from under cooked chicken legs and choke on a chicken bone",
"1:59am (+Sebastian-Legend) rc i know why u picks your nouse because its cheaper than a tissue kleenex you god damn jew",
"<+Sebastian-Legend> it cost everyday wake up with the right vission of life, face troubles and sometimes hells when i was on the jungle or africa but a life worths it",
"<+oskr> TSM - you give your protein strictly to males? <+Sebastian-Legend> of course man <+Sebastian-Legend> if u give this proteins to girls they gona come out hair on theyr female parts and gona look bad",
"6:56pm (@{51}crp) you need a towel? 6:56pm (+Yugde) to clean your tears 6:57pm (+Yugde) then il clean my cums on your face pussy",
"(+Chuntaro-Style) il take your face until the ground and make you regret for your words son",
"(+Chuntaro-Style) hey seven to go sit ur fat ass on the couch and eat cheetos before you gets hurt",
"-02:26:58- (+Chuntaro-Style) nice man / -02:27:06- (+Chuntaro-Style) pug of family lion members",
"<YDT10> have you ever travelled to Mars before? / <Chuntaro-Style> people has invited me / <Chuntaro-Style> but i got no time",
"<YDT10> do you have streets in mexico named after you? / <Chuntaro-Style> not yet / <Chuntaro-Style> but i hope / <Chuntaro-Style> one day / <Chuntaro-Style> with the respect of the people / <Chuntaro-Style> and the luck of a champion",
"<Chuntaro-Style> im honest / <Chuntaro-Style> you was like my / <Chuntaro-Style> 45505 woman on my bed / <Chuntaro-Style> im a profesional mmodel",
"<YDT10> how big is your dick? / <Chuntaro-Style> like 30 inches",
"<Chuntaro-Style> sorry yes im spic then / <YDT10> are you king spic? / <Chuntaro-Style> do u wana dance / <Chuntaro-Style> some cumbia / <Chuntaro-Style> i have all the power on my speakers dancing cumbia fuck the neighbords",
"<Chuntaro-Style> when i travel to america / <Chuntaro-Style> when my weding / <Chuntaro-Style> i get robed by 2 niggers",
"<YDT10> youre married? / <Chuntaro-Style> i was / <Chuntaro-Style> a long time ago / <Chuntaro-Style> but she died / <YDT10> just like James Bond. / <Chuntaro-Style> whos that?",
"<Chuntaro-Style> i recomend after everygame a protein milkshake of black wheyprotein u can add some ice of chocolate if youre not very fat, this is cos u lost all your sugars and energys playing a game like this",
"9:10pm (+Chuntaro-Style) WHEN YOU go to jail and came back victorious to real life, call your life sicks 9:10pm (+Chuntaro-Style) piece of shit 9:11pm (+Chuntaro-Style) weak mother fucker fake",
"9:11pm (+Chuntaro-Style) whos this loser man 9:11pm (+Chuntaro-Style) out of my face now 9:12pm (+Chuntaro-Style) or i punch you 9:12pm (+CK) lmao 9:13pm (+Chuntaro-Style) *punches in stomach* 9:13pm (+Chuntaro-Style) he was warned",
"<+sebastian> my master is nfrs sly and xebo <+sebastian> xebo the master of speed and movement <+sebastian> nfrs the master of disaster <+sebastian> and sly the wise master of the woods",
"<+sebastian> dont ever challenge a legend",
"<+Chuntaro-Style> yo yo respresent my mexican people over the world listen to my rhimes niggers cant rap anymore cos mexicans are taking the throne the throne",
"<+Chuntaro-Style> i will come back soon friend [01:37:57:AM] <+Chuntaro-Style> at night u will see my face when u sleep",
"<+Chuntaro-Style> my girl is roxate <+Chuntaro-Style> she smy real ut girlfeiend man",
"(+RickJames) Does TSM ever go on TS? He must be hillarious / -23:55:39- (+Chuntaro-Style) i speak on xbox live with normal people not with weirdos on ut",
"<Chuntaro-Style> youre my princess",
"<YDT10> http://themasterofmetal.blogspot.com/ / <YDT10> I also like to read this blog. / <Chuntaro-Style> whata fuck / <Chuntaro-Style> whos that / <YDT10> it is Omar Alex Herrera / <YDT10> my friend / <Chuntaro-Style> stop it now / <Chuntaro-Style> fucking whore / <YDT10> stop what now / <Chuntaro-Style> stop stiking your nouses on people bussines",
"<Chuntaro-Style> im sebastian / <Chuntaro-Style> im tsm cousin / <Chuntaro-Style> tsm doesnt play anymore / <Chuntaro-Style> he retired / <Chuntaro-Style> dont tell this to anybody / <YDT10> are you the cousin that fucks TSM up the ass? / <Chuntaro-Style> im his cousing yes",
"<Chuntaro-Style> solo cant even have sex he got diatribes",
"<Chuntaro-Style> tickle my dick / <Chuntaro-Style> crazy weirdo creepo",
"12:15am (+Chuntaro-Style) lost by desuqlification",
"12:31am (+Chuntaro-Style) horchata is a nice mexican drink, u drink the pee pee of the americans for some dollars bitch 12:31am (+Chuntaro-Style) go back to mexico worm fucker",
"-02:08:16- (+soifon) who are u? / -02:08:29- (+Chuntaro-Style) i am the legendary player who come from mexico to conquest america",
"(+Chuntaro-Style) smokes is bad / (+LaG|Se7eN) Chuntaro-Style you think he will have cancerous? / (+Chuntaro-Style) 80% of chances of get cancerouses",
"(+Chuntaro-Style) you cant mix up asteroids with alcohol or veins explotes like a missiles friend",
"(+Chuntaro-Style) *servers fine mango milkshake with yogurt*",
"(+Chuntaro-Style) sly is fucking handsome dont be jealous",
"<Chuntaro-Style> diphalous <Chuntaro-Style> tell them to remove the ban, i reconected with a old ip that is banned <Chuntaro-Style> so i cant get in <Chuntaro-Style> and i dont know how to change back to my last ip * Chuntaro-Style is now known as LAG <LAG> HOW CAN I DO YTHE BAR * LAG is now known as LaG|TSM <LaG|TSM> im on lag now * LaG|TSM has quit (Quit)",
"5:40pm (+LaG|TSM) when i come up to your drive through window i want my hamburgese with extra lettuce fat piggy officer you got no real job diabitec spic ball of grass",
"<+LaG|TSM> let me dip my dick in enchilada sauce before you sucking it to get a little taste of mexico before i make cums over your face fat boy",
"(+LaG|TSM) did you see how solo gets fucked by his younger son on the anus / (+LaG|TSM) with his little thined erected dick",
"(+LaG|TSM) watch the tongue of your mom she licks my anus like a cheap hooker from the ny streets",
"(+LaG|TSM) diphalous u wana taste this pie ufucking fatso",
"<+LaG|TsM> dont become a creepo like toms and his deathly cancerous vicious",
"8:54pm (+nfrs) *oink oink* 8:54pm (+LaG|TsM) is solos bastard son around here 8:55pm (+LaG|TsM) i hear his screamy pigs",
"<+LaG|TsM> i bet the only guys who going to solo parties is that bastard song he have and his special fatso hamburguese of chesse with little candles over them like a birthdates cake",
"9:08pm (+LaG|TsM) wana see the fathamburguese of solos 9:08pm (+LaG|TsM) [photo of nude man with erection removed]",
"9:11pm (+LaG|TsM) +spiting on your face* 9:11pm (+LaG|TsM) suck my big mexican and muscular dick",
"<+LaG|TsM> the mosquito was fuckingme so hard",
"(+LaG|TsM) not even on his little town cos seven doesnt like people / (+LaG|TsM) scarry man living alone on a boat jerkess all day watching the naturalece",
"9:04pm (+LaG|TsM) your mom likes my gorila ass 9:04pm (+LaG|TsM) muscular strong and big 9:04pm (+LaG|TsM) you cant even lift that nerdo computer u got with anime pictures around the monitor",
"9:01pm (+LaG|TsM) il fuck your mom with my fingers dv 9:02pm (+LaG|TsM) theyre large and beuatifull like a the pianist making melodies at the piano",
"10:22pm (LaG|TsM) whata scared mexicant porky pussy solo diabrites ill make him watch me fuck his bastard son and he will enjoy the show",
"10:29pm (LaG|TsM) have u ever have online sex friend 10:30pm (LaG|TsM) cos i just have sex on a rpg online friend on my iphone app it is very nice",
"<+LaG|TsM> habbos better than ut anyway <+LaG|TsM> is the new shit <+LaG|TsM> on online gaming <+LaG|TsM> www.habbo.com",
"7:45pm (+LaG|TsM) *claping the hands so strong the wind starts to shake*",
"(LaG|TsM) i say no nfrs im bussy right now im studying my tesis for doctor",
"3:32pm (LaG|TsM) WATCH MY VIDEO FRIENDS http://www.youtube.com/watch?v=Em-mGcD1WGc",
"<+LaG|TsM> if u need a real challenge get the fuck outa my dick",
"<+LaG|TsM> il spit on your face | <@tom> no | <@tom> u type in a box | <+LaG|TsM> il spit | <@tom> ok | <+LaG|TsM> spit the computer and imagine is your smoker junky face",
"<LaG|TsM> il eat your dick so hard u cant never sit again fucker",
"[LaG|TsM]: yo flux im bigger than u friend even if u do 1000 pectoral presses and eat all asteroids",
"<LaG|TsM> cos im a model <LaG|TsM> i have my hands like a french model",
"<LaG|TsM> i beat a whellchairs can beat the shit out of that loser imperium",
"<LaG|TsM> i made my hands at the stetic girls like it, dont be jealous friend",
"10:13pm (+LaG|TsM) zkyp why dont u bring here your mom so she can suck my big muscular atlethic dick",
"10:08pm (+LaG|TsM) you can go everyday to the beaches 10:08pm (+LaG|TsM) and get your own robster at the sea 10:09pm (+TAKENBYTSM-LEGEND) did your robsters look like this 10:09pm (+TAKENBYTSM-LEGEND) [photo of nude men removed] 10:09pm (+LaG|TsM) yyes 10:09pm (+LaG|TsM) friend 10:09pm (+LaG|TsM) no wait why u show that pic of the gays",
"10:32pm (+LaG|TsM) listen to my rhymes, the lucky leprechaunt rhymes, nigger cant rap anymore cos mexican are taking the throne 10:32pm (+LaG|TsM) the throne the throne 10:34pm (+LaG|TsM) too pac was my friend on the streets he died, now hes alive and he lives on my axiles",
"5:15pm (LaG|TsM) u wana to get your face fucked like an egg who falls of the kitchen accesories prick",
"8:37pm (+THECAPTURESMASTER) i just buy this pohone so i can plau habbos while in jungles of africa making medicines friend http://www.flickr.com/photos/tooms/5441391377/",
"10:21pm (+THECAPTURESMASTER) ***dancing on carp the dance of the chicken with chicken custome and the picture of spico face transalated well to custome****",
"10:36pm (+THECAPTURESMASTER) i gota clean my belly 10:36pm (+THECAPTURESMASTER) of the cums 10:36pm (+THECAPTURESMASTER) friend 10:36pm (+THECAPTURESMASTER) holdon",
"10:42pm (+THECAPTURESMASTER) spico salad of shit",
"<+THECAPTURESMASTER> ratface u look like those guys who stole all the auto-stereos from the cars",
"8:38pm (+TSM-LEGEND) tang drew u an egg licker jew wop popsicle",
"(+THECAPTURESMASTER) lick my obliques",
"(+LaG|TSM) let me transalates",
"1:41am (+LaG|TSM) «« TSM played in 2833 pugs in #tdmpickups «» Weekly: 0.23 «» Captained: 399 «» Avg Pick: 1.2 «» Lamer Count: 8 «» Last: 89wks 3days 3hrs 16mins 41secs ago »»» 1:41am (+LaG|TSM) u see im better than u 1:41am (+LaG|TSM) dumb little nigger 1:41am (+LaG|TSM) fat ball pancake grass face",
"2:45am (LaG|TSM) goodbye friend let the starts shines your mind and the fishes teach u a lesson",
"2:29pm (THECAPTURESMASTER) my mouse is full of grass 2:29pm (THECAPTURESMASTER) cant play very well",
"3:30pm (THECAPTURESMASTER) friend they 3:30pm (THECAPTURESMASTER) put the injustice belt on me 3:30pm (THECAPTURESMASTER) like the heroe who wants to save the lands of rufians",
"<+TSM-SKILLSMASTER> if u were here il kick your door until u getout of that psycho hole u hiden away from society",
"<+enj0ythesilence> Was so fun that echo wanted my real msn <+enj0ythesilence> and facebook <+enj0ythesilence> to jerkess well",
"<+enj0ythesilence> yo solo becarefull cos im about to rape your bastar child <+enj0ythesilence> with my mexican <+enj0ythesilence> flag <+enj0ythesilence> u fatso <+enj0ythesilence> u can run but u cant hide from me",
"<+TSM-SKILLSMASTER> that nfrs is playing his thricky leprechaunt games with me again / <+TSM-SKILLSMASTER> they dance theyr shoes at the rythm of the devil / <+TSM-SKILLSMASTER> the leprechaunt always have the last card in hand",
"12:07am (TSM-SKILLSMASTER) i just comebackk from a bubbles bath, my abs looking good",
"<+TSM-SKILLSMASTER> i do it unpropused",
"4:23pm (+TSM-SKILLSMASTER) whata fucking loser and he sounds in ts like a whitegangster loser without niggas",


];

const quotesLower = quotes.map(function(value) {
      return value.toLowerCase();
    });

function getRandomInt(max) {
  return Math.floor(Math.random() * Math.floor(max));
}

function isString(x) {
  return Object.prototype.toString.call(x) === "[object String]"
}

function toLower(x) {
	return x.toLowerCase();
}

client.on("message", (message) => {
	
	if (!message.content.startsWith(config.prefix) || message.author.bot) return;
	
	var args = message.content.slice(config.prefix.length).trim().split(/ +/g);
	const command = args.shift().toLowerCase();
	
	var argsLower = args.map(function(value) {
      return value.toLowerCase();
    });
	
	args = argsLower;

  if(message.content.startsWith(config.prefix + "prefix")) {
	if(message.author.id !== config.ownerID) return;
  // Gets the prefix from the command (eg. "!prefix +" it will take the "+" from it)
	let newPrefix = message.content.split(" ").slice(1, 2)[0];
  // change the configuration in memory
	config.prefix = newPrefix;

  // Now we have to save the file.
	fs.writeFile("./config.json", JSON.stringify(config), (err) => console.error);
	}
  
  if (command === 'ping') {
    message.channel.send("pong!");
  } else
  if (command === 'blah') {
    message.channel.send("meh!");
  }
  
  if (command === "asl") {
  let [age, sex, location] = args;
  message.reply(`Hello ${message.author.username}, I see you're a ${age} year old ${sex} from ${location}. Wanna date?`);
  }
  
  if (command === 'quote' || command === 'q') {
	if (!isNaN(args[0]) && args[0] <= quotes.length) {
		quoteNum = parseInt(args[0]);
		message.channel.send("Quote " + quoteNum + ": " + quotes[quoteNum - 1]);
	}
	else if (isString(args[0])) {
		let matches = quotesLower.filter(s => s.includes(args[0]));
		var matchesNum = getRandomInt(matches.length);
		if (matches.length > 0) {
			quoteNum = quotesLower.indexOf(matches[matchesNum]) + 1;
			message.channel.send("Quote " + quoteNum + ": " + quotes[quoteNum-1]);
		}
		else {
			message.channel.send("No matches found.");
		}
	}
	else {
	var quoteNum = getRandomInt(quotes.length) + 1;
    message.channel.send("Quote " + quoteNum + ": " + quotes[quoteNum - 1]);
	}
  }
});

client.login(process.env.BOT_TOKEN);
